language: c
compiler: 
  - gcc

script:
  - cmake .
  - make

before_install:
  - sudo apt-get install -y libevent-dev python2.7-dev libssl-dev libgeoip-dev libpcre3-dev libconfig-dev libmaxminddb-dev mmdb-bin