language: c
compiler: 
  - gcc

script:
  - echo "Libevent"
  - cd libevent
  - cmake .
  - make
  - mv lib/* ..
  - echo "Main"
  - cd ..
  - cmake -DBUILD_WITH_LOCAL_LIBEVENT=ON .
  - make

before_install:
  - git clone https://github.com/libevent/libevent.git
  - sudo add-apt-repository -y ppa:maxmind/ppa
  - sudo apt-get -y update
  - sudo apt-get install -y python2.7-dev libssl-dev libgeoip-dev libpcre3-dev libconfig-dev libmaxminddb0 libmaxminddb-dev mmdb-bin